import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { readFileSync } from 'node:fs';

const read = name => readFileSync(new URL(`./${name}`, import.meta.url), 'utf8');
describe('native conversation 2x2 contract', () => {
  it('keeps one native list and one native pane for every preference pair', () => {
    const app = read('MailApp.jsx'); const list = read('MessageList.jsx');
    assert.match(app, /<MessageList\s*\/>/);
    assert.match(app, /conversationReaderViewEnabled\s*&&\s*conversationId\s*\?\s*['"]conversation['"]\s*:\s*['"]single['"]/);
    assert.match(list, /function ThreadRow/);
    assert.doesNotMatch(list, /GroupedConversationList/);
    assert.match(list, /accountOwnAddresses\(childAccount, msg\)/);
    assert.match(list, /MessageDirection direction=\{childDirection\}/);
    assert.match(list, /accounts=\{accounts\}/);
    assert.doesNotMatch(list, /accounts\.flatMap/);
    assert.match(list, /if \(threadedView\) params\.threaded = ['"]true['"]/);
    assert.match(list, /const threadKey = message\.thread_key \|\| message\.thread_id \|\| message\.id/);
    assert.match(list, /api\.getThread\(threadKey, effectiveFolder, false, message\.account_id \|\| selectedAccountId \|\| null\)/);
    assert.doesNotMatch(list, /conversationApi\.list/);
    assert.doesNotMatch(list, /conversationListToThreadRows/);
  });
  it('resolves every selected physical copy through the CE identity endpoint (OFF/ON blocker)', () => {
    const app = read('MailApp.jsx');
    assert.match(app, /conversationApi\.resolveMessage\(selectedMessageId, selected\?\.account_id \|\| null\)/);
    assert.match(app, /setConversationId\(resolved\.conversation_id\)/);
    assert.match(app, /setTargetLogicalMessageId\(resolved\.logical_message_id/);
    assert.match(app, /id: resolved\.physical_copy_id \|\| resolved\.id \|\| selectedMessageId/);
    assert.match(app, /accountId: resolved\.account_id \|\| resolved\.accountId \|\| null/);
    assert.match(app, /selectedConversationCopy=\{selectedConversationCopy\}/);
    assert.match(app, /thread_key: copy\.threadKey \|\| copy\.threadId \|\| null/);
    assert.match(app, /conversationId/);
    assert.match(app, /data-ce-resolution-error/);
    assert.match(app, /Conversation reader resolution failed/);
  });
  it('uses compact native-pane message cards and per-message reply targets', () => {
    const reader = read('ConversationReader.jsx'); const item = read('ConversationMessage.jsx');
    assert.match(reader, /setExpanded\(initialConversationExpansion\(messages, targetLogicalMessageId\)\)/);
    assert.match(reader, /initialConversationTarget\(messages, targetLogicalMessageId\)/);
    assert.match(reader, /filter\(copy => String\(copy\.accountId \?\? copy\.account_id\) === String\(selectedAccountId\)\)/);
    assert.match(reader, /api\.getMessageBody\(physicalCopyId, remoteImages\)/);
    assert.match(reader, /mailflow:conversation-refresh/);
    assert.match(reader, /sameAccountCopies\.find\(item => String\(item\.id\) === String\(selectedCopyId\)\)/);
    assert.match(reader, /currentStatus\?\.error/);
    assert.match(reader, /scrollIntoView\(\{ block: 'start' \}\)/);
    assert.doesNotMatch(reader, /message\.direction/);
    assert.match(reader, /toggleConversationExpansion\(previous, id\)/);
    assert.match(item, /MessageToolbar/);
    const presentation = read('MessagePresentation.jsx');
    const toolbar = read('MessageToolbar.jsx');
    assert.match(toolbar, /data-conversation-message-actions/);
    assert.match(toolbar, /reply-options/);
    assert.match(toolbar, /data-message-action=\{action\}/);
    assert.match(item, /logicalMessageId: message\.id/);
    assert.match(item, /preferredAccountCopy\(message, selectedAccountId, selectedCopyId\)/);
    assert.match(item, /physicalCopyDirection\(copy, account\)/);
    const direction = read('../utils/conversationDirection.js');
    assert.match(direction, /String\(copy\.accountId \?\? copy\.account_id\) !== String\(account\.id\)\) return null/);
    assert.doesNotMatch(item, /messageDirection\(message\.direction\)/);
    assert.match(item, /MessageBodyRenderer/);
    assert.match(item, /showQuotedTextLabel=\{t\('conversation\.showQuotedText'\)\}/);
    assert.match(item, /hideQuotedTextLabel=\{t\('conversation\.hideQuotedText'\)\}/);
    assert.match(item, /data-conversation-message-state/);
    assert.match(item, /data-conversation-message-toggle/);
    assert.match(item, /role="button"/);
    assert.match(item, /window\.getSelection/);
    assert.match(item, /background: 'var\(--message-body-bg\)'/);
    assert.match(item, /item\.email \|\| item\.address/);
    assert.match(item, /copy\.fromEmail && \(outgoing \|\| copy\.fromName\)/);
    assert.match(item, /body\?\.html \?\? body\?\.body_html/);
    assert.match(item, /body\?\.text \?\? body\?\.body_text/);
    assert.match(item, /title=\{recipient \|\| accountLabel\}/);
    assert.match(item, /address\(copy\.cc\)/);
    assert.match(item, /!expanded && summary/);
    assert.match(item, /expanded && hasAccountCopy && <MessageToolbar/);
    assert.match(item, /if \(!hasAccountCopy\) return/);
    assert.match(item, /href=\{canAccessCopy && physicalCopyId/);
    assert.match(item, /physicalCopyId=\{copy\.id\} canAccessCopy=\{hasAccountCopy\}/);
    assert.match(item, /scope: 'THIS_COPY', copyId: copy\.id, logicalMessageId: message\.id/);
    assert.match(item, /conversationApi\.archive\(conversationId, actionOptions\)/);
    assert.match(item, /conversationApi\.move\(conversationId, folder, actionOptions\)/);
    assert.match(item, /conversationApi\.delete\(conversationId, actionOptions\)/);
    assert.match(item, /conversationApi\.setRead\(conversationId, isRead, actionOptions\)/);
    assert.match(item, /conversationApi\.setStarred\(conversationId/);
    assert.match(item, /\{expanded && hasAccountCopy && <MessageToolbar[\s\S]*?\/>\}[\s\S]*?<div[\s\S]*?data-conversation-message-toggle="true"/);
    assert.match(item, /expanded && <div data-conversation-message-expanded-content/);
    assert.match(item, /copy\.listUnsubscribe/);
    assert.match(item, /<AttachmentList attachments=\{attachments\}/);
    const pane = read('MessagePane.jsx');
    assert.match(pane, /<MessageToolbar/);
    assert.match(presentation, /if \(!normalized\) return null/);
  });
});
